names:
- Curves
- HighwaySymbols
- Informational
- MileMarkers
- Regulatory
- SpeedLimits
- StopSigns
- TrafficLights
- Warnings
nc: 9
path: /opt/dlami/nvme/Jacob/wvsignclassification/data/processed/wv
train: train/images
val: val/images
