names:
- chevron
- curve
- deerCrossing
- guide
- other
- pedestrianCrossing
- railroadCrossing
- speedLimit
- stop
- warning
- yield
nc: 11
path: /opt/dlami/nvme/Jacob/wvsignclassification/data/processed/wv
train: train/images
val: val/images
