names:
- chevron
- curve
- deerCrossing
- guide
- other
- pedestrianCrossing
- railroadCrossing
- speedLimit
- stop
- warning
- yield
nc: 11
path: C:\Users\jrj00048\Projects\wvsignclassification\data\processed\wv
train: train/images
val: val/images
